config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  namespace :v1 do
    resources :movies  do
      resources :reviews
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # post '/movies/:movie_id/reviews', to: 'movies#create_review'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "movies#index"
   resources :movies do
    resources :reviews
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
require_relative '../../app/services/tmdb/all_service'
require_relative '../../app/services/tmdb/detail_service'
require_relative '../../app/services/tmdb/search_service'
class MoviesController < ApplicationController
  # before_action :authenticate_user!
  def index
    if params[:movie_title].present?
      @movies = Tmdb::SearchService.execute(title: params[:movie_title])
    else
      @movies = Tmdb::AllService.execute()
    end
  end

  def show
    @a= Tmdb::DetailService.execute(id: params[:id])
    @movie=Movie.find_by(mid: params[:id])
    if @movie.nil?
      @moviecreate = Tmdb::DetailService.execute(id: params[:id])
    end
  end

  def new

  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!
  def create
    @movie = fetch_movie(params[:movie_id])

    @moviecreate = Movie.find_by(mid: @movie['id']) || Movie.create(mid: @movie['id'], title: @movie['title'], original_title: @movie['original_title'], overview: @movie['overview'], poster: @movie['poster_path'], popularity: @movie['popularity'])

    @reviewcreate = current_user.reviews.build(review_params.merge(movie_id: @moviecreate.id))

  if @reviewcreate.save
    flash.now[:alert] = 'Review success.'
    else
    flash.now[:alert] = 'Review could not be saved.'

  end
  redirect_to movie_path(id: @moviecreate.mid)
  end


  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.update(review_params)

    redirect_to movie_path(id: @movie.mid)
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to movie_path(id: @movie.mid)
  end


  private

  def fetch_movie(movie_id)
    Tmdb::DetailService.execute(id: movie_id)
  end

  def review_params
    params.require(:review).permit(:description)

  end

end

app/controllers/v1/reviews_controller.rb
class V1::ReviewsController < ApplicationController
  # before_action :authenticate_user!, only: [:create]
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user_using_api_key
    def index
      #  movie = Movie.find(params[:movie_id])

      movie = Movie.find_by(mid: params[:movie_id])
      if movie.nil?

        @movie = fetch_movie(params[:movie_id])
        # binding.irb
            if @movie['id'].nil?
              render json: { error: 'movie not found in tmdb' }, status: :not_found
              else
                  @movie = Movie.find_by(mid: @movie['id']) || Movie.create(mid: @movie['id'], title: @movie['title'], original_title: @movie['original_title'], overview: @movie['overview'], poster: @movie['poster_path'], popularity: @movie['popularity'])

                  reviews = @movie.reviews.map { |review| { user_id: review.user_id, thereview: review.description } }
                  render json: {TotalReview: reviews.count, movie_id: @movie.mid, reviews: reviews }
            end
            else
            reviews = movie.reviews.map { |review| { user_id: review.user_id, thereview: review.description } }
            render json: {TotalReview: reviews.count, movie_id: movie.mid, reviews: reviews }
          end
    end

def create
  movie = Movie.find_by(mid: params[:movie_id])
  unless current_user
    render json: { error: 'User not authenticated' }, status: :unauthorized
    return
  end

  if movie.nil?
    @movie = fetch_movie(params[:movie_id])
          # if response.code == 404
           if @movie['id'].nil?
            render json: { error: 'movie not found in tmdb' }, status: :not_found
              else
                @movie = Movie.find_by(mid: @movie['id']) || Movie.create(mid: @movie['id'], title: @movie['title'], original_title: @movie['original_title'], overview: @movie['overview'], poster: @movie['poster_path'], popularity: @movie['popularity'])
                review = @movie.reviews.build(review_params)
                review.user_id = current_user.id
                if review.save
                  render json: { message: 'Review created successfully', review_id: review.id }, status: :created
                else
                  render json: { error: 'Failed to create review', errors: review.errors.full_messages }, status: :unprocessable_entity
                end
          end
  else

    review = movie.reviews.build(review_params)
    review.user_id = current_user.id

    if review.save
      render json: { message: 'Review created successfully', review_id: review.id }, status: :created
    else
      render json: { error: 'Failed to create review', errors: review.errors.full_messages }, status: :unprocessable_entity
    end
  end
end

private

def authenticate_user_using_api_key
  api_key = request.headers['x-api-key']
  @current_user = User.find_by(apikey: api_key)
  unless @current_user
    render json: { error: 'User not authenticated' }, status: :unauthorized
  end
  # api_key = request.headers['x-api-key']
  # unless api_key && user = User.find_by(apikey: api_key)
  #   render json: { error: 'Unauthorized' }, status: :unauthorized
  # end
end

def review_params
  params.require(:review).permit(:description)
end


def fetch_movie(movie_id)
  Tmdb::DetailService.execute(id: movie_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/v1/reviews_helper.rb
module V1::ReviewsHelper
end

app/views/home/index.html.erb
<div class="container mx-auto max-w-screen-lg">
  <div class="border-b border-grey-lighter py-16 lg:py-20">
    <div>
      <img src="/assets/img/author.png" class="h-16 w-16" alt="author" />
    </div>
    <h1
      class="pt-3 font-body text-4xl font-semibold text-primary dark:text-white md:text-5xl lg:text-6xl"
    >
      Hi, I’m John Doe.
    </h1>
    <p class="pt-3 font-body text-xl font-light text-primary dark:text-white">
      A software engineer and open-source advocate enjoying the sunny life in Barcelona, Spain.
    </p>
    <a
      href="/"
      class="mt-12 block bg-secondary px-10 py-4 text-center font-body text-xl font-semibold text-white transition-colors hover:bg-green sm:inline-block sm:text-left sm:text-2xl"
    >
      Say Hello!
    </a>
  </div>

  <div class="border-b border-grey-lighter py-16 lg:py-20">
    <div class="flex items-center pb-6">
      <img src="/assets/img/icon-story.png" alt="icon story" />
      <h3
        class="ml-3 font-body text-2xl font-semibold text-primary dark:text-white"
      >
        My Story
      </h3>
    </div>
    <div>
      <p class="font-body font-light text-primary dark:text-white">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Nibh mauris cursus
        mattis molestie. Et leo duis ut diam. Sit amet tellus cras adipiscing
        enim eu turpis. Adipiscing at in tellus integer feugiat.
        <br />
        <br />
        Maecenas accumsan lacus vel facilisis. Eget egestas purus viverra
        accumsan in nisl nisi scelerisque eu. Non tellus orci ac auctor augue
        mauris augue neque gravida. Auctor augue mauris augue neque gravida in
        fermentum et sollicitudin. Tempus urna et pharetra pharetra massa massa
        ultricies mi quis. Amet mauris commodo quis imperdiet massa. Integer
        vitae justo eget magna fermentum iaculis eu non.
      </p>
    </div>
  </div>

  <div class="py-16 lg:py-20">
    <div class="flex items-center pb-6">
      <img src="/assets/img/icon-story.png" alt="icon story" />
      <h3
        class="ml-3 font-body text-2xl font-semibold text-primary dark:text-white"
      >
        My Story
      </h3>
      <a
        href="/blog"
        class="flex items-center pl-10 font-body italic text-green transition-colors hover:text-secondary dark:text-green-light dark:hover:text-secondary"
      >
        All posts
        <img
          src="/assets/img/long-arrow-right.png"
          class="ml-3"
          alt="arrow right"
        />
      </a>
    </div>
    <div class="pt-8">
      <div class="border-b border-grey-lighter pb-8">
        <span
          class="mb-4 inline-block rounded-full bg-green-light px-2 py-1 font-body text-sm text-green"
          >category</span
        >
        <a
          href="/post"
          class="block font-body text-lg font-semibold text-primary transition-colors hover:text-green dark:text-white dark:hover:text-secondary"
          >Quis hendrerit dolor magna eget est lorem ipsum dolor sit</a
        >
        <div class="flex items-center pt-4">
          <p class="pr-2 font-body font-light text-primary dark:text-white">
            July 19, 2020
          </p>
          <span class="font-body text-grey dark:text-white">//</span>
          <p class="pl-2 font-body font-light text-primary dark:text-white">
            4 min read
          </p>
        </div>
      </div>
      <div class="border-b border-grey-lighter pt-10 pb-8">
        <div class="flex items-center">
          <span
            class="mb-4 inline-block rounded-full bg-grey-light px-2 py-1 font-body text-sm text-blue-dark"
            >category</span
          >
          <span
            class="mb-4 ml-4 inline-block rounded-full bg-yellow-light px-2 py-1 font-body text-sm text-yellow-dark"
            >category</span
          >
        </div>
        <a
          href="/post"
          class="block font-body text-lg font-semibold text-primary transition-colors hover:text-green dark:text-white dark:hover:text-secondary"
          >Senectus et netus et malesuada fames ac turpis egestas integer</a
        >
        <div class="flex items-center pt-4">
          <p class="pr-2 font-body font-light text-primary dark:text-white">
            June 30, 2020
          </p>
          <span class="font-body text-grey dark:text-white">//</span>
          <p class="pl-2 font-body font-light text-primary dark:text-white">
            5 min read
          </p>
        </div>
      </div>
      <div class="border-b border-grey-lighter pt-10 pb-8">
        <span
          class="mb-4 inline-block rounded-full bg-blue-light px-2 py-1 font-body text-sm text-blue"
          >category</span
        >
        <a
          href="/post"
          class="block font-body text-lg font-semibold text-primary transition-colors hover:text-green dark:text-white dark:hover:text-secondary"
          >Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies</a
        >
        <div class="flex items-center pt-4">
          <p class="pr-2 font-body font-light text-primary dark:text-white">
            June 26, 2020
          </p>
          <span class="font-body text-grey dark:text-white">//</span>
          <p class="pl-2 font-body font-light text-primary dark:text-white">
            3 min read
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="pb-16 lg:pb-20">
    <div class="flex items-center pb-6">
      <img src="/assets/img/icon-project.png" alt="icon story" />
      <h3
        class="ml-3 font-body text-2xl font-semibold text-primary dark:text-white"
      >
        My Projects
      </h3>
    </div>
    <div>
      
      <a
        href=" / "
        class="mb-6 flex items-center justify-between border border-grey-lighter px-4 py-4 sm:px-6"
      >
        <span class="w-9/10 pr-8">
          <h4
            class="font-body text-lg font-semibold text-primary dark:text-white"
          >
            TailwindCSS
          </h4>
          <p class="font-body font-light text-primary dark:text-white">
            Rapidly build modern websites without ever leaving your HTML.
          </p>
        </span>
        <span class="w-1/10">
          <img src="/assets/img/chevron-right.png" class="mx-auto" alt="chevron right" />
        </span>
      </a>
      
      <a
        href=" / "
        class="mb-6 flex items-center justify-between border border-grey-lighter px-4 py-4 sm:px-6"
      >
        <span class="w-9/10 pr-8">
          <h4
            class="font-body text-lg font-semibold text-primary dark:text-white"
          >
            Maizzle
          </h4>
          <p class="font-body font-light text-primary dark:text-white">
            Framework for Rapid Email Prototyping
          </p>
        </span>
        <span class="w-1/10">
          <img src="/assets/img/chevron-right.png" class="mx-auto" alt="chevron right" />
        </span>
      </a>
      
      <a
        href=" / "
        class="mb-6 flex items-center justify-between border border-grey-lighter px-4 py-4 sm:px-6"
      >
        <span class="w-9/10 pr-8">
          <h4
            class="font-body text-lg font-semibold text-primary dark:text-white"
          >
            Alpine.js
          </h4>
          <p class="font-body font-light text-primary dark:text-white">
            Think of it like Tailwind for JavaScript.
          </p>
        </span>
        <span class="w-1/10">
          <img src="/assets/img/chevron-right.png" class="mx-auto" alt="chevron right" />
        </span>
      </a>
      
      <a
        href=" / "
        class="mb-6 flex items-center justify-between border border-grey-lighter px-4 py-4 sm:px-6"
      >
        <span class="w-9/10 pr-8">
          <h4
            class="font-body text-lg font-semibold text-primary dark:text-white"
          >
            PostCSS
          </h4>
          <p class="font-body font-light text-primary dark:text-white">
            A tool for transforming CSS with JavaScript
          </p>
        </span>
        <span class="w-1/10">
          <img src="/assets/img/chevron-right.png" class="mx-auto" alt="chevron right" />
        </span>
      </a>
      
    </div>
  </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesReviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<div class="container mx-auto px-4">
  <!-- Search bar at the top -->
  <div class="mt-10 mb-8">
    <h2 class="text-3xl font-bold mb-4">Find Movie</h2>
    <%= form_tag(movies_path, method: :get) do %>
      <div class="flex items-center">
        <%= text_field_tag :movie_title, params[:movie_title], placeholder: 'Enter movie title', class: "rounded-l-lg p-4 border-t border-b border-l border-gray-400 text-gray-800 bg-white focus:outline-none focus:border-blue-500 flex-grow", style: "height: 40px;" %>
        <%= submit_tag 'Search', class: "px-6 py-2 bg-blue-500 text-white rounded-r-lg hover:bg-blue-600 ml-2" %>
      </div>
    <% end %>
  </div>


  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
    <% if @movies.any? %>
      <% @movies.each do |movie| %>
        <div class="relative group border rounded-lg overflow-hidden bg-gray-800 shadow-md transition-transform duration-300 transform hover:scale-105">
          <% if movie['poster_path'].present? %>
            <%= link_to movie_path(movie['id']), class: "block" do %>
              <%= image_tag("https://image.tmdb.org/t/p/w500#{movie['poster_path']}", alt: movie['title'], class: "object-cover w-full h-48 sm:h-64") %>
            <% end %>
          <% end %>
          <div class="p-4 bg-white-900"> 
            <%= link_to movie_path(movie['id']), class: "block text-lg font-semibold hover:text-red-600" do %>
              <%= movie['title'] %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="mt-4">No movies found</p>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

app/views/movies/show.html.erb
<% if @moviecreate.present? %>
<div class="container mx-auto mt-2 lg:flex justify-center items-center">
  <!-- Movie Poster -->
  <div class="lg:mr-10">
    <%= image_tag("https://image.tmdb.org/t/p/w300#{@moviecreate['poster_path']}", alt: @moviecreate['title'], class: "mb-4") %>
  </div>
  

  <div class="lg:w-3/4">
    <h1 class="text-3xl font-bold mb-4"><%= @moviecreate['title'] %></h1>
    <p class="text-lg"><strong>Original Title:</strong> <%= @moviecreate['original_title'] %></p>
    <p class="text-lg"><strong>Release Date:</strong> <%= @moviecreate['release_date'] %></p>
    <p class="text-lg"><strong>Popularity:</strong> <%= @moviecreate['popularity'] %></p>
    <p class="text-lg mt-8"><strong>Description:</strong> <%= @moviecreate['overview'] %></p>
  </div>
</div>
<% else %>
<div class="container mx-auto mt-2 lg:flex justify-center items-center">

  <div class="lg:mr-10">
    <%= image_tag("https://image.tmdb.org/t/p/w300#{@movie['poster']}", alt: @movie['title'], class: "mb-4") %>
  </div>
  

  <div class="lg:w-3/4">
    <h1 class="text-3xl font-bold mb-4"><%= @movie.title %></h1>
    <p class="text-lg"><strong>Original Title:</strong> <%= @movie.original_title %></p>
    <p class="text-lg"><strong>Popularity:</strong> <%= @movie.popularity %></p>
    <p class="text-lg mt-8"><strong>Description:</strong> <%= @movie.overview %></p>
  </div>
</div>
<%end%>
<!---displaying reviews---->
<% if @movie.present? && @movie.reviews.present? %>
<div class="container mx-auto mt-8 space-y-4">
  <% @movie.reviews.each do |review| %>
    <div class="bg-gray-800 rounded-lg shadow-md hover:shadow-lg transition duration-300 ease-in-out p-4 flex items-start space-x-4">
      <div class="flex-grow">
        <p class="text-lg text-white"><%= review.user.email.split("@").first %><br><%= review.description %></p>
      </div>
      <% if review.user == current_user %>
        <div class="flex-none space-x-2">
          <%= link_to 'Edit', edit_movie_review_path(movie_id: @movie.id, id: review.id), class: "text-blue-500 hover:text-blue-700" %>
          <%= link_to 'Delete', movie_review_path(movie_id: @movie.id, id: review.id), method: :delete, data: { turbo_confirm: 'Are you sure?', "turbo-method": :delete }, class: "text-red-500 hover:text-red-700" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<% end %>
<!---form for review--->
<div class="container mx-auto mt-8 p-6 bg-gray-100 rounded-lg shadow-lg">
  <%= simple_form_for Review.new, url: movie_reviews_path(movie_id: @movie&.mid || @moviecreate['id']), method: :post do |f| %>
    <%= f.input :description, label: 'Review', placeholder: 'Add a comment', label_html: { class: 'text-lg font-semibold text-gray-700' }, input_html: { class: "bg-white border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full p-3 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-500 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
    <%= f.submit 'Post', class: "bg-blue-500 hover:bg-blue-600 text-white font-semibold px-4 py-2 rounded-md mt-2 transition duration-300 ease-in-out" %>
  <% end %>
</div>

app/views/movies/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>

app/views/reviews/edit.html.erb
<h1 class="text-2xl mb-4 font-bold">Edit Review</h1>

<div class="md:w-[40%]">
  <%= simple_form_for [@movie, @review], url: movie_review_path(@movie, @review), method: :patch do |f| %>
    <%= f.input :description, label: 'Review', placeholder: 'edit a review...', label_html: {class: 'mt-4'}, input_html: {class: 'mt-2 md:max-w-[50%]'} %>
    <%= f.submit 'Update', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800' %>
  <% end %>
</div>



app/views/reviews/new.html.erb

<%= form_with(model: @review, url: movie_reviews_path(@movie['id']), method: :post) do |form| %>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  
  <%= form.submit 'Post' %>
<% end %>

app/views/shared/_footer.html.erb
<div class="container mx-auto">
    <div class="flex flex-col items-center justify-between border-t border-grey-lighter py-10 sm:flex-row sm:py-12">
      <div class="mr-auto flex flex-col items-center sm:flex-row">
        <a href="/" class="mr-auto sm:mr-6">
          <img src="/assets/img/logo.svg" alt="logo" />
        </a>
        <p class="pt-5 font-body font-light text-primary dark:text-white sm:pt-0">
          ©2020 John Doe.
        </p>
      </div>
      <div class="mr-auto flex items-center pt-5 sm:mr-0 sm:pt-0">

        <a href="https://github.com/ " target="_blank">
          <i
              class="text-4xl text-primary dark:text-white pl-5 hover:text-secondary dark:hover:text-secondary transition-colors bx bxl-github"></i>
        </a>

        <a href="https://codepen.io/ " target="_blank">
          <i
              class="text-4xl text-primary dark:text-white pl-5 hover:text-secondary dark:hover:text-secondary transition-colors bx bxl-codepen"></i>
        </a>

        <a href="https://www.linkedin.com/ " target="_blank">
          <i
              class="text-4xl text-primary dark:text-white pl-5 hover:text-secondary dark:hover:text-secondary transition-colors bx bxl-linkedin"></i>
        </a>

      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
 <div class="container mx-auto">
  <div class="flex items-center justify-between py-6 lg:py-10">
    <a href="/" class="flex items-center">
      <span href="/" class="mr-2">
        <img src="/assets/img/author.png" />
      </span>
      <p
        class="hidden font-body text-2xl font-bold text-primary dark:text-white lg:block"
      >
        Medium Clone
      </p>
    </a>
    <div class="flex items-center lg:hidden">
      <i
        class="bx mr-8 cursor-pointer text-3xl text-primary dark:text-white"
        @click="themeSwitch()"
        :class="isDarkMode ? 'bxs-sun' : 'bxs-moon'"
      ></i>

      <svg
        width="24"
        height="15"
        xmlns="http://www.w3.org/2000/svg"
        @click="isMobileMenuOpen = true"
        class="fill-current text-primary dark:text-white"
      >
        <g fill-rule="evenodd">
          <rect width="24" height="3" rx="1.5" />
          <rect x="8" y="6" width="16" height="3" rx="1.5" />
          <rect x="4" y="12" width="20" height="3" rx="1.5" />
        </g>
      </svg>
    </div>
    <div class="hidden lg:block">
      <ul class="flex items-center">
        
        <li class="group relative mr-6 mb-1">
          <div
            class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow"
          ></div>
          <%= link_to 'Home',root_path, class:"relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"%>
        </li>
        
        <li class="group relative mr-6 mb-1">
          <div
            class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow"
          ></div>
          <%= link_to 'Write a review on our site', home_index_path, class:"relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"%>
        </li>
        
        <li class="group relative mr-6 mb-1">
          <div
            class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow"
          ></div>
        <% if !user_signed_in? %>
          <%= link_to 'Sign in', new_user_session_path, class:"relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"%>
        <%end%>
        </li>
        
        <li class="group relative mr-6 mb-1">
          <div
            class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow"
          ></div>
            <% if user_signed_in? %>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary", data: {turbo_confirm: "are you sure?", turbo_method: :delete} %>

            <% else %>
              <%= link_to 'Sign up', new_user_registration_path, class: "relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"%>
            <% end %>        
        </li>
        
        <li>
          <i
            class="bx cursor-pointer text-3xl text-primary dark:text-white"
            @click="themeSwitch()"
            :class="isDarkMode ? 'bxs-sun' : 'bxs-moon'"
          ></i>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/v1/reviews/index.html.erb
<h1>V1::Reviews#index</h1>
<p>Find me in app/views/v1/reviews/index.html.erb</p>